-- Run once in Supabase SQL Editor to set up the RAG vector store.

create extension if not exists vector;

create table if not exists document_chunks (
  id bigint generated by default as identity primary key,
  user_id text not null,
  source text not null,
  content text not null,
  embedding vector(384) not null,
  created_at timestamptz not null default now()
);

create index if not exists document_chunks_user_id_idx on document_chunks (user_id);

create index if not exists document_chunks_embedding_idx on document_chunks
  using hnsw (embedding vector_cosine_ops);

-- RPC used by the backend for similarity search (pgvector's <=> operator
-- isn't reachable through the normal PostgREST table filters).
create or replace function match_document_chunks(
  query_embedding vector(384),
  match_user_id text,
  match_count int default 4
)
returns table (
  id bigint,
  source text,
  content text,
  similarity float
)
language sql stable
as $$
  select
    document_chunks.id,
    document_chunks.source,
    document_chunks.content,
    1 - (document_chunks.embedding <=> query_embedding) as similarity
  from document_chunks
  where document_chunks.user_id = match_user_id
  order by document_chunks.embedding <=> query_embedding
  limit match_count;
$$;
